name: Update Changelog
on:
  pull_request:
    types: [closed]

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged_at != null
    steps:
    - uses: actions/checkout@v2
    - name: Get Next Version
      uses: "fcurella/gh-action-next-version@main"
      id: nextversion
      with:
        part: "patch"
    - name: Update Changelog
      uses: "fcurella/gh-action-update-changelog@main"
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        changelogPath: "CHANGELOG.rst"
        changelogLine : 4
        currentVersion: ${{ steps.nextversion.outputs.currentVersion }}
        nextVersion: ${{ steps.nextversion.outputs.nextVersion }}
    - name: Bump version
      uses: "fcurella/gh-action-bump2version@main"
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        part: "patch"
